server:
    port: 8083
    compression:
        enabled: true

spring:
    servlet:
        multipart:
            max-request-size: 15MB
            max-file-size: 20MB
            file-size-threshold: 2KB
            enabled: true
    application:
        name: api-ambcard
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
file:
    upload-dir: ~/uploads

